### ISSUE TITLE
Compatibility with streaming through MPC-HC (Media Player Classic)

### ISSUE THREAD

**Issue by Slyceth** [streamlink/windows-builds#4]
### Build flavor

Installer - Python 3.10 - x86_64 (64 bit)

### Description

As an avid Firefox user and Chrome avoider, I'd still like to make use of the new VSR features that can be enabled within MPC.

In other words, I'd like to be able to stream for example Twitch streams through MPC so the upscaling can do its work. Youtube streaming already works through yt-dlp.

I'd like some specific steps but compatibility would be nice!

**Comment by bastimeyer** [comment]
Wrong place. This is the Streamlink Windows builds issue tracker. Use the Streamlink discussion forum for support questions.
