### ISSUE TITLE
Update Winget registry to latest version (6.3.1-1)

### ISSUE THREAD

**Issue by Kaosarbitrium** [streamlink/windows-builds#8]
### Checklist

- [X] I understand that this is the issue tracker for Streamlink's Windows builds and not for Streamlink itself
- [X] I am using the latest stable or nightly release

### Build flavor

Installer - Latest Python - x86_64 (64 bit)

### Build version

6.2.1-1

### Description

The Winget repository simply needs to be updated to point towards the latest stable build. It's currently pointing towards build 6.2.1-1. Not sure who handles that process.

**Comment by bastimeyer** [comment]
https://streamlink.github.io/install.html#package-availability

> Packaging is not done by the Streamlink maintainers themselves except for the [PyPI package](https://streamlink.github.io/install.html#id4), the [Windows installers + portable builds](https://streamlink.github.io/install.html#windows-binaries), and the [Linux AppImages](https://streamlink.github.io/install.html#linux-appimages).
> If a packaged release of Streamlink is not available for your operating system / distro or your system's architecture, or if it's out of date or broken, then please **contact the respective package maintainers or package-repository maintainers of your operating system / distro**, as it's up to them to add, update, or fix those packages.

**Comment by bastimeyer** [comment]
https://github.com/microsoft/winget-pkgs/issues?q=streamlink

**Comment by Kaosarbitrium** [comment]
Ah, thank you. Apologies for the ignorance regarding the matter.

**Comment by bastimeyer** [comment]
All good. Whenever I post a response with only a link (and quote), then it's usually because I don't want to waste anyone's time, as the information is already there.

As you've already seen yourself, there's a PR for `6.3.1-1` on their repo.
