### ISSUE TITLE
Streamlink can no longer open afreecatv streams

### ISSUE THREAD

**Issue by mesaryn** [streamlink/windows-builds#9]
### Checklist

- [X] I understand that this is the issue tracker for Streamlink's Windows builds and not for Streamlink itself
- [X] I am using the latest stable or nightly release

### Build flavor

Installer - Latest Python - x86_64 (64 bit)

### Build version

streamlink-6.6.1-1-py312-x86_64

### Description

I was using the older version 6.1, and it seems Afreecatv may have change something on their end, it worked few hours ago, but no longer work now, then I later installed this latest 6.6.1 python312 version to see if it helps, but it still cannot open Afreecatv's streams.

**Comment by bastimeyer** [comment]
> * I understand that this is the issue tracker for Streamlink's Windows builds and not for Streamlink itself
